filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.py"
    exclude:
      - ".watchcode.log"
      - "*.pyc"
      - "__pycache__"
    exclude_gitignore: true
    match_mode: "gitlike"

tasks:
  default:
    fileset: default
    commands:
      - "py.test -v"
    clear_screen: true
    queue_events: false

default_task: default
log: false
sound: false
notifications: false
