language: python

python:
  - "2.7"
  - "3.6"

env:
  - REQUIREMENTS="minimal"
  - REQUIREMENTS="latest"

install:
  - |
    pip install -r requirements.txt -I
    if [ $REQUIREMENTS = "minimal" ]; then
        pip install watchdog==0.9.0 pyyaml==3.0
    fi
    pip freeze

script:
  - pytest
