FileSets:
  Default:
    Include:
      - ".watchcode.yaml"
      - "*.py"
    Exclude:
    MatchMode: "unix"

Tasks:
  Default:
    Commands:
      - "echo 'starting build...'"
      - "sleep 5"
      - 'echo "stopped build"'
      - echo another test
    ClearScreen: true
    QueueEvents: true

Targets:
  Default:
    FileSet: Default
    Task: Default

DefaultTarget: Default
