filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.py"
      - "*"
    exclude:
      - ".watchcode.log"
    exclude_gitignore: true
    match_mode: "fnmatch"

tasks:
  default:
    fileset: default
    commands:
      - "py.test -s"
    clear_screen: true
    queue_events: false

default_task: default
log: false
