filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.py"
    exclude:
    match_mode: "gitlike"

tasks:
  default:
    commands:
      - "py.test"
    clear_screen: true
    queue_events: false


targets:
  default:
    fileset: default
    task: default

default_target: default
log_all_events: false
