FileSets:
  Default:
    Include:
      - ".watchcode.yaml"
      - "*.py"
    Exclude:
    MatchMode: "fnmatch"

Tasks:
  Default:
    Commands:
      - "py.test"
    ClearScreen: false
    QueueEvents: false


Targets:
  Default:
    FileSet: Default
    Task: Default

DefaultTarget: Default
ShowAllEvents: true
