filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.py"
      - "*"
    exclude:
      - ".watchcode.log"
    exclude_gitignore: true
    match_mode: "fnmatch"

tasks:
  default:
    commands:
      - "py.test"
    clear_screen: true
    queue_events: false


targets:
  default:
    fileset: default
    task: default

default_target: default
log_all_events: false
